version: '2'
services:
  web:
    image: "PHP:7.0"
    ports:
      - "3000:3000"
    links:
      - db
      - memcached
      - elasticsearch
    volumes:
      - ./:/code
    working_dir: /code
    command: php -S 0.0.0.0:3000

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: yourgreatapp
      MYSQL_USER: yourgreatapp
      MYSQL_PASSWORD: yourgreatapp
      MYSQL_HOST: ""
    mem_limit: 1000000000
    ports:
      - "33333:3306"

  elasticsearch:
    image: "elasticsearch:1.3"

  memcached:
    image: memcached

