version: '2'
services:
  web:
    image: "php:7.0"
    ports:
      - "3000:3000"
    links:
      - db
      - memcached
      - elasticsearch
    volumes:
      - ./:/code
    working_dir: /code
    command: php -S 0.0.0.0:3000
    container_name: web

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: yourgreatapp
      MYSQL_USER: yourgreatapp
      MYSQL_PASSWORD: yourgreatapp
      MYSQL_HOST: ""
    mem_limit: 1000000000
    ports:
      - "3306:3306"
    container_name: db

  elasticsearch:
    image: "elasticsearch:2.4"
    container_name: elasticsearch

  memcached:
    image: "memcached:1.4"
    container_name: memcached

